### ISSUE TITLE
Wix Pages Wisdom Well: High Level and Monthly or Quarterly

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#20]
Wisdom Well landing page: 
Wix: Social and email sign ups. This should capture SEO and be where we will send everyone to purchase the event. Button up top and then what to expect, time to gather, give you skills to host, what you get, etc, more buttons. 
They will have two options to purchase for each event, monthly or quarterly. (see links above)
If they purchase the quarterly plan, they will get access to any past events - i.e. they purchase in Feb, they will get Jan, Feb, and March

**Comment by wileyandco** [comment]
@CarrieTHA These are up at 
https://www.thehumanarray.com/wisdom-well-about and
https://www.thehumanarray.com/wisdom-well-options
for you to peruse and fuss with copy. Let me know if the branding feels good and I'll upload the icons and colors to canva for you.

**Comment by CarrieTHA** [comment]
YAY! Looking through now. I love the bright colors and icons. Sending to Sarah so she can take a look too.

**Comment by CarrieTHA** [comment]
Sending the email way since I don't think Sarah is in the Github yet. Here
is my feedback / revisions:

- On mobile, the menu for the site is in blue - can we make that white like
on desktop?
- For the header image, that maroon color feels too heavy. Can we do a blue
(for water) and then do the logo in a purple color (purple for wisdom :D)?
- I like the idea of the emphasis lines around the description section and
the first button, but they don't feel quite right. Could they echo the
swirliness of the WW logo rather than being straight? They feel a bit too
cutesy rather than fun.
- For that same section, I am updating copy (because I really like the Big
Idea at the bottom). Is that section flexible enough that if I add more
copy it will adjust for me?
- Icons:
     - Can we swap the sun for a moon? More connected to months
     - Social space can that be a talk bubble for comments like in the
community instead of a confetti burst?
- The flowers / suns prior to the Well-keepers - I like the idea of keeping
a flowy, fun vibe with mimicking the logo flow feel for these parts and
emphasis like the first section. Can these also be something more tied to
the feeling of the WW logo?
- The pink feels a smidge too bright, but I think adjusting the other
things first and seeing how the pink feels makes the most sense rather than
focusing on that first. Let me know what you think.

Let me know if you have any questions! I am around today if you want to
call / chat!



*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray

**Comment by CarrieTHA** [comment]
Also, can we create a carousel under "what is the Wisdom Well" that has
each of the months and the theme with a little blurb so that that they can
get a taste of what each month will offer?

i.e.
head: January: Nourish through community
subhead: tbd

head: February: Nourish through ritual
subhead: tbd

head: March: Nourish your energy
subhead: tbd

After the Well-keepers, can we add a section that gives a preview of the
events for the rest of the year?

Make this a ritual for 2024
Here's a preview of all upcoming gatherings
Spring: Create
Summer: Flow
Fall: Play


*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray

**Comment by wileyandco** [comment]
@CarrieTHA 
Just putting a note in here. These are updated. And I switched out the pink for a bright purple instead.

**Comment by wileyandco** [comment]
Hey @CarrieTHA , Sending a quick note. I went in to change the icons (done!) and found a bunch of broken text and sections. I cleaned them up and remade the new one. When you add in text, make sure you're doing it in desktop mode only or it won't show up on all breakpoints. There was still lorem ipsum on desktop and at the top had messed up the order of the text boxes where you had added new text in a different view. Let me know if you're still mixing it up in here and I can take a look before it goes out ❤️



![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/9aae65b7-6c47-4585-8486-a92eb86bb7ba)
![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/b938451e-1716-4dda-b9a4-4b0de73e0d95)
![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/fbe429c4-206b-4448-b686-c33369f18ef3)
![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/9013d09f-1cad-4ed3-a84f-95bcd2839490)

**Comment by CarrieTHA** [comment]
Oh thank you! I was going to drop you a note to take a look at my
work 😅 Thank you for that tip / note. I will be sure to do that. Thank you
for cleaning it up. I did add in a bunch of FAQs and I don't see them on
the desktop version. Did I mess that up? Was hoping to offer more specifics
via an FAQ accordion.


*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray

**Comment by wileyandco** [comment]
Oh yep @CarrieTHA , I didn't scroll far enough, that one is only showing up on mobile. I'll fuss with it and republish right now.

**Comment by CarrieTHA** [comment]
Awesome, thanks!


*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray

**Comment by wileyandco** [comment]
@CarrieTHA All updated for you again.

**Comment by CarrieTHA** [comment]
Hi! A couple of small things (and one bigger one LOL)

- I must've broken the links 😬 All of the buttons to /wisdom-well-options
don't take you to that page any longer
- For the Well-keepers section, there are a couple of things happening
1. The copy on mobile is in the right order, but it reverses on desktop
(the intent was for Well-keepers to come first with a description
underneath it)
2. The sun icons above this section just aren't landing for us. Other
ideas? Perhaps adding the THA logo there instead?
3. In desktop mode, there is a lot of space before that section. Can we
tighten it up a bit?
- The "Interested in a fully virtual Wisdom Well?" is fine, but if you
think it could look any better (because it absolutely can 😅) I would
appreciate some touches there.

Also, if you could upload the new logos into Canva when you have a chance
so I can work on social / the community space, I would appreciate it!


*Carrie Allen*
Founder
thehumanarray.com
IG: @thehumanarray

**Comment by wileyandco** [comment]
@CarrieTHA 

Links appear to be working. Wix hiccup?

1: all set

2: Actually, the THA logo makes perfect sense here; happy to just do that. Stars_2.png from your updated canva kit here would also work: https://www.canva.com/brand/kAF2T5a3gF4

3: it got stretched. all good now

4: virtual: agreed this and the corporate section could be columns next to each other in a better looking section. Will need a bit of time to play with that. 

Let me know if Sarah needs a new invite to this - I think they expire, but want to make sure she's included.

**Comment by CarrieTHA** [comment]
Sounds great. 
4: are fine enough, so whenever you get to it! 

Also, now that we are ready, can we add a menu item on the site for this? Titled: Wisdom Well

**Comment by wileyandco** [comment]
@CarrieTHA All set on the menu. Will do for those sections.

**Comment by wileyandco** [comment]
@CarrieTHA https://www.thehumanarray.com/wisdom-well-about is updated with new sections for Corporate and Virtual at the bottom. I also hid the previous text sections in case we want them for callouts or something else.
