### ISSUE TITLE
Templates for host script, invitation tips, menu itself, menu recipes

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#22]

**Comment by wileyandco** [comment]
@CarrieTHA This is next on my list to professional-up the event materials. These will probably have the same header/look/feel. Just wanted to ping you in case you've started them in canvas I can't see. Also, if there is something else up next for priority, let me know.

**Comment by CarrieTHA** [comment]
Hi! You are a great mind reader! I was actually thinking that we would shift you to work on the new website image / structure since I think I can just adjust the invitation that you provided already. I have a copy I made where I played with some other ideas that I wanted to share with you. I will make some comments in Canva and hopefully you can see them! I will create another issue for the website.
