### ISSUE TITLE
prints for wisdom well hosts

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#24]
prints for Welcome and Guests

**Comment by wileyandco** [comment]
@CarrieTHA 
These are here: https://www.canva.com/design/DAF3iXnivEw/Ul7dI0rRVa-yiqFhyPg2oA/edit

Feeling like the table center one should be bright and the guest ones should be dark (since they will be next to food and water and also so they aren't too distracting). Made the backs white though for notes and callout if desired. 
Thinking to ensure they feel really nice considering the $150 fee we could use Moo (which also makes it easy to print out 1 welcome for every 10 or 20 or whatnot guest ones). These are set up with bleeds so are all all set for you to do so if you like them. 

https://www.moo.com/us/postcards/standard

Then two options for holders. Wooden ones too rustic or the right vibe for being earthy?

https://www.amazon.com/Holders-Trapezoidal-Support-Birthday-Decoration/dp/B0B9WTGXGF/ref=sr_1_21?crid=20OCQ5303TZYR&keywords=wooden%2Btable%2Bcard%2Bholders%2B4%2Binches&qid=1703093814&s=home-garden&sprefix=wooden%2Btable%2Bcard%2Bcolders%2B4%2Binches%2Cgarden%2C135&sr=1-21&th=1

https://www.amazon.com/Jofefe-Premium-Holders-Picture-Thanksgiving/dp/B09HQ91XTK/ref=sr_1_9?crid=3OOV9LNH9LIQ7&keywords=table+number+holder+wood&qid=1703093715&sprefix=table+number+holder+wood%2Caps%2C116&sr=8-9

**Comment by CarrieTHA** [comment]
Ooohhh!! This is great. Agree on the coloring. I like the wood ones and if
they're holding the bright blue, I think it could be a good balance. I'll
show to Sarah and Gina tomorrow and see what they think!

**Comment by CarrieTHA** [comment]
Talked about the table card concept with Sarah and Gina. We all like the idea and it felt a little corporatey to have them in the holders. So what do you think about this? 

https://www.canva.com/design/DAF3ojqHZWE/e3sAuHZRAxcx0T6wsPjVBg/edit?utm_content=DAF3ojqHZWE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Placesetting: Print a card to put on top of each plate / placesetting that says welcome on the front and has their notes option on the back. We would still print these on nice stock and send!
Page 1: Front (what you would initially see) 
Page 2: Back (where they could write notes)

Card deck: I believe that the questions are going to change each month, or maybe each quarter. So we thought we could send the 3 cards with the questions to each host so that they can "collect them all" as well as use them the night of the gathering as the "talking stick" to pass around the table for each person to answer. 
Page 3: We would have one branded front of the card - aka the deck design
Page 4, 5, & 6: This is just me playing. I like the dark color! And perhaps the background of the questions changes with the theme, so they would collect as well as be able to group them (like suits!) for their future gatherings if they wanted. But not sure how you would want to play with that concept. 

We probably need to tighten up our plan for the questions to get this to the finish line. There was talk of affirmations or quotes on these as well to provide inspiration, but I think I would rather keep it simple to start unless you have some inspiration for what could be included in a way that doesn't distract from the main purpose of being prompted by the question.

**Comment by wileyandco** [comment]
@CarrieTHA I like the idea of it just being a placesetting/plate topper - I'd just make them skinnier in that case. This size? https://www.moo.com/us/postcards/rack-cards

Then the cards should be even smaller, maybe actual playing card size (similar to moo card size actually) so they feel more collectable? Or the moo square cards and could with either send them a little box where they can keep them (which of course you only have to send the first time they host). Maybe one plainer one in the front that says "Thank you for hosting. Collect all the conversation starters when you host again and use them anytime" type thing. 

As far as branding for each event, could just put the theme on each one, though each question says nourish too. I do love a color-coding. Let me know what you think for sizes and I'll play a little. 

I like the affirmations or quotes and they feed into your brand in general. They could be a little extra (1-3) just for the hosts or to give out at the party as a little gift to each guest at the end of the night (put this in an email or post so the hosts know).

<img width="1389" alt="Screen Shot 2023-12-21 at 5 21 20 PM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/3f43eaaa-3466-4b26-ba89-35dbc8523c0a">
Even come in green - one of the WW brand colors! 

Also, please don't use ellipsis on them (they are considered rude to many people). :)

**Comment by CarrieTHA** [comment]
Hi! I like this idea. I like the box as well. As long as folks can read the writing, I think that is my only concern with the smaller cards. I just bought a box of Talking Points Family and the size and font size are good. I think it is this size. I also like the affirmations as a little gift for each guest. Let me think a smidge more about the cards and what we would want to do with them. I don't want to go too big before we figure out what works and what doesn't. We could always backfill if that feels good to provide. 

Also, yes on the skinnier version for the place setting. Perhaps to start we just include a quote or affirmation on the place setting and see what the feedback is to make individual affirmation/quote cards. 

Noted on the ellipsis :D

**Comment by wileyandco** [comment]
@CarrieTHA It's business card size so if they aren't too long, it'll be fine. I'll wait for you to think on it a bit more. I like having an affirmation at the bottom and with moo we could have a different one on each, which is also a fun conversation starter at the beginning of the night?

**Comment by wileyandco** [comment]
long cards for each place same layout

business cards for three questions
affirmation under logo

**Comment by wileyandco** [comment]
@CarrieTHA https://www.canva.com/design/DAF48bIz9fA/KW8uvIJgvHa88MDtN-k2SQ/edit?utm_content=DAF48bIz9fA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
is the longer place setting Guest cards

and 
https://www.canva.com/design/DAF48oOWykQ/vka94Wj_oMlbWAcaFfG3aw/edit?utm_content=DAF48oOWykQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
is the updated Question cards. I added little numbers to the bottom to not only make them seem like a series or real product, but so it has that collect them all and mix or match like a deck feeling for as you continue on with them. Could do little pull a card or three on social late next year when there are a bunch.

(to keep the links in a findable place). Export as "PDF Print", check "crop marks and bleed" and toggle to "CMYK" for Moo or let me know if you want me to do the ordering and send to your house.

Boxes link: https://www.moo.com/us/display-boxes
Here is the layout I double-checked in the boxes if they use them to stand them up. 

![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/7977f29d-3aa6-4c44-b2a9-ca2e92f2dd6f)
