### ISSUE TITLE
make forms consistent, jotform email flow

### ISSUE THREAD

**Issue by wileyandco** [wileyandco/thehumanarray#39]

**Comment by wileyandco** [comment]
@CarrieTHA 

FYI for later. Not sure if Sarah would want to add in this tech, but maybe Meg could take point on updating it as this scales.
Approval flow exists for the initial application form:

<img width="1262" alt="Screen Shot 2024-04-03 at 2 37 09 PM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/129b21e7-d94c-450d-b0b8-2e9d166b087b">

**Comment by CarrieTHA** [comment]
Ooooohhhh this is good. I haven't played with that yet. I will check it out. 

Also, I recreated the application in Jotform so they will look consistent. I also added some Hubspot magic so it will create a deal for us so we can start to see where people are getting stuck. Can you update the application page to be this form instead?

https://form.jotform.com/240936089888173

**Comment by CarrieTHA** [comment]
Ok I just played with these settings on the new application form that I created above. I think it will send to hello@thehumanarray and they don't have to login to Jotform in order to approve. 

Next step is customizing the email that sends from Jotform. It would be OH SO nice for this to work so that we can then trigger the email to send with the way to schedule their call. Sarah is not interested in creating a block of time for this and it gives me extreme anxiety to create a cumbersome process for the Catalyst. So I am working on that. LOL 

Could you work on branding/formatting the email and then I will work on how we get them to agree on how to schedule interviews?

**Comment by wileyandco** [comment]
@CarrieTHA Great! The link is updated on the catalyst-learn-more page and the explore pricing page - thanks for setting it up. We can use jotform for these emails to make the flow easier and less expensive, but just fyi it's like ancient and basically made with html. For scheduling we can just make a button that goes to another form, maybe where they pick two or three times that work for them? These will take me a minute to set up - there's no drag and drop lol. 
These are the emails I got from your updates:
<img width="453" alt="Screen Shot 2024-04-03 at 9 53 18 PM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/89e64957-faa4-4fdc-8dec-d52c3ca8ce9a">
<img width="1524" alt="Screen Shot 2024-04-03 at 9 24 35 PM" src="https://github.com/wileyandco/thehumanarray/assets/78058722/90e768a0-f960-4da1-b106-781a6a97ed97">

Do you want to assign someone else to write or review the copy for these, perhaps in a google doc? The welcome email especially seems like a good opportunity for someone wordier than I am. Happy to organize the buckets and slim them down afterward, or just do them all if you want though :)

**Comment by wileyandco** [comment]
@CarrieTHA 
I think a lot of the ones after this flow can be done within mighty as chats/events or in Robin's case, be a personal email that goes out. The referral process will need some branding and organizing and a form at least. Thoughts?

**Comment by CarrieTHA** [comment]
Absolutely! I think we leverage what we can from here while we need to and then we move over to Hubspot / MN. I agree that Robin's should be from her personal email, so I am going to get her set up in Hubspot so that we can create templates for her there so she can easily see who she needs to reach out to and then pop in the template. I also think her sending a chat in MN is important too, I just think it needs to be both as I have noticed that not all folks are responding within MN. I feel this is a constant hurdle and learning about how we would want to build the tech ourselves. LOL

As for the Jotform emails, yes, this list looks right and we may be able to trigger the Welcome through a different platform using Zapier. I will see if I can play with it a bit. Also, I like your idea of a way for them to select a couple of timeframes that are preferable so that Meg/Sarah have a place to start. Is it possible to embed the form in the email - similar to how our Approve/Deny buttons work?


That reminds me, I am going to add a field to the form to ask for referral / how they heard about us. 

For the rest of the process of referrals, we were going to tell Catalysts to just send them through the application for now and include their name as a referral. I know the Catalysts would love something to be able to use to share with their audience, so I think some copy and potentially an image or so would help them share. Is there something else you were thinking about branding and organizing/form for the referrals?

And YES to assigning someone else the copy for the Welcome email. Let me see who I can give that to :D

**Comment by wileyandco** [comment]
Jotform has scheduling forms. It looks like we’d just have to add text that
says tell us two (or three times) that work for you and repeat the
selecting section. Would work from a button in the email, not the email
itself.
https://www.jotform.com/online-meeting-scheduler/?acc=main&adgroup=159724948756&matchtype=p&network=g&device=m&devicemodel=&extension_id=&feeditemid=&target_id=kwd-341578831417&target=&loc_interest=&loc_physical=9005574&placement=&utm_source=adwords&utm_campaign=21085931506&utm_medium=cpc&utm_term=meeting%20scheduling%20tool&utm_content=692924158258&utm_scp=&gad_source=1&gbraid=0AAAAAC-d9aniwLTRfSa788q0bkoCkYdwr&gclid=Cj0KCQjwn7mwBhCiARIsAGoxjaLQP6cjzFKkGIyHb0M0V2PP7pELJYwiXZTf2KPN9MiXIrbZumV6GJEaAjH0EALw_wcB


Awesome, these sound great:
Field for referral name and having them send to the application, no emails
needed.

We could add a canva template and just include a plain photo option for
them in mighty resources that says join me on the human array. I suppose I
was thinking for further down the line when referrals count towards
contribution

Zap to better email for the welcome one from hubspot. This would have to be
zapped anyway I’d think since it’s contingent upon them paying on mighty or
wherever?









*Jeannette Wiley Detwiler*
Owner & Designer

wileyand.co
***@***.***
linkedin.com/in/jeannettewiley
cell: 315-283-0648 <315-283-0648>

**Comment by wileyandco** [comment]
Also, just thinking that if you are making zaps, we should probably make
one or two for the reminders for has filled out the form, but hasn’t paid
yet, if possible. Since the follow up otherwise would be only manual.




*Jeannette Wiley Detwiler*
Owner & Designer

wileyand.co
***@***.***
linkedin.com/in/jeannettewiley
cell: 315-283-0648 <315-283-0648>

**Comment by CarrieTHA** [comment]
So the annoying part is that Hubspot wants us to pay BIG bucks to be able
to trigger emails 😭 So yes...and we have to figure out how. I think I can
trigger them through Gmail instead which has pros and cons obviously. Some
technical hiccups while we stay frugal 😬

**Comment by wileyandco** [comment]
Makes total sense. If it’s too much effort at the moment, honestly, the
best way to get someone to complete sign-up is to follow through personally
so it’s good we can just do that.




*Jeannette Wiley Detwiler*
Owner & Designer

wileyand.co
***@***.***
linkedin.com/in/jeannettewiley
cell: 315-283-0648 <315-283-0648>

**Comment by wileyandco** [comment]
@CarrieTHA just an fyi that I'm organizing the visuals and copy of this flow in this new document so that we can do an audit and easily track changes for copy, if needed, for you or whomever is assigned to that as things keep progressing and changing. 

https://docs.google.com/document/d/1QC8z27h2miMfbjOS9waiOi60-MCMyultA5nbY5xBKb0/edit?usp=sharing

**Comment by wileyandco** [comment]
Need to fuss with these again later and add a link in the intake approval for all types of plans, not just fuels

**Comment by wileyandco** [comment]
![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/3edd60ef-3a4c-43c6-9d03-11fb02a99cab)



![Image](https://github.com/wileyandco/thehumanarray/assets/78058722/95bfa135-1754-4ce7-a031-36a3637cecb8)

@CarrieTHA  Right now there is an extra approval in there so we can send an email to Sarah and Meg to update their calendar slots for each individual week (if that's amenable), which we can customize with the reminder text. Then, their hubspot or something could be updated and linked from the plain text one if we wanted to avoid setting up the calendar form. 

It's confusing, but automated. If you want to talk through it on Monday, we can :)
